#+title: Readme
This repo is incomplete and nonfunctional as of [2023-06-26 Mon 14:30]. If you happen to find this and want to help, feel free to open an issue.
* Brainstorming

** Where to install the extracted files
*** Make udev rules
#+begin_quote
    If you just need a single udev rule set up and don’t mind using a different method, there is a attribute you can set in your configuration.nix file called services.udev.extraRules. It takes a string but you can create multiple rules there.

      services.udev.extraRules = ''
        # Your rule goes here
      '';

    The issue may be that the rule has a hardcoded path to /sbin/udevcontrol in it based on the error message you’ve shown, where as you would want to refer to the derivation when writing the rule if you need to execute a particular program. That’s just a guess on my part, usually there are rewrite tools that kick in automatically but they may not extend to this context.[fn:1]
#+end_quote
*** [?] Maybe move =/usr/= dirs into =/out/=?
:LOGBOOK:
- State "[?]"        from              [2023-06-26 Mon 14:22]
:END:
*** [?] Resolving dependencies
:LOGBOOK:
- State "[?]"        from              [2023-06-26 Mon 16:12]
:END:
**** TODO [2023-06-26 Mon 16:12]  Stuck on =libQt5RemoteObjects.so.5=
:LOGBOOK:
- State "TODO"       from              [2023-06-27 Tue 01:06]
:END:
  #+begin_src bash
error: auto-patchelf could not satisfy dependency libQt5RemoteObjects.so.5 wanted by /nix/store/1xanmzd7bgs8cfpg041jjm5gnk8m6b08-Huion-Kamvas-Driver/usr/lib/huiontablet/qml/QtQml/RemoteObjects/libqtqmlremoteobjects.so
  #+end_src
  Maybe try to copy the packaging style of [[https://search.nixos.org/packages?channel=unstable&show=qt6.qtremoteobjects&from=0&size=50&sort=relevance&type=packages&query=remote+objects+qt][qt6's version]]?
  According to the discord, this is a consequence of a missing package in nixpkgs.[fn:2]

* Footnotes
[fn:2] https://discord.com/channels/568306982717751326/570351749848891393/1123012159471878144

[fn:1] https://discourse.nixos.org/t/creating-a-custom-udev-rule/14569
